// This script is used for creating payments in NetSuite.
var PaymentURl='https://api-3t.sandbox.paypal.com/nvp';
var body='';
body+='&USER=vamsi-facilitator_api1.netscoretech.com';
body+='&PWD=BJR5MNVD3QRW65TU';
body+='&SIGNATURE=AxWyhYIg8D5KIXCwlhj3d1yBOn5zA2AugWOKqAHk0m2a2LNdYhF9xUIi';
body+='&METHOD=DoDirectPayment';
body+='&PAYMENTACTION=Authorization';
body+='&IPADDRESS=192.168.0.1';
body+='&AMT=15.00';
body+='&ACCT=6011111111111117';
body+='&EXPDATE=042021';
body+='&CVV2=123';
body+='&FIRSTNAME=Vamshi';
body+='&LASTNAME=Krishna';
body+='&STREET=1MainSt.';
body+='&CITY=SanJose';
body+='&STATE=CA';
body+='&ZIP=95131';
body+='&COUNTRYCODE=US';
body+='&VERSION=115';
var Request=nlapiRequestURL(PaymentURl,body,null,'POST');
var requestBody=Request.getBody().split('&');
var lengthArray=requestBody.length;
var TranIdSplit=requestBody[lengthArray-1].split('=');
var TranId=TranIdSplit[1];
nlapiLogExecution('Debug','TranId',TranId);
var XXX=0;

var PaymentURl='https://api-3t.sandbox.paypal.com/nvp';
var body='';
body+='&USER=vamsi-facilitator_api1.netscoretech.com';
body+='&PWD=BJR5MNVD3QRW65TU';
body+='&SIGNATURE=AxWyhYIg8D5KIXCwlhj3d1yBOn5zA2AugWOKqAHk0m2a2LNdYhF9xUIi';
body+='&METHOD=DoCapture';
body+='&AUTHORIZATIONID='+TranId;
body+='&AMT=10.00';
body+='&COMPLETETYPE=NotComplete';
body+='&VERSION=115';
var Request=nlapiRequestURL(PaymentURl,body,null,'POST');
var requestBody=Request.getBody();
nlapiLogExecution('Debug','DoCapture',requestBody);
var XXX=0;


var PaymentURl='https://api-3t.sandbox.paypal.com/nvp';
var body='';
body+='&USER=vamsi-facilitator_api1.netscoretech.com';
body+='&PWD=BJR5MNVD3QRW65TU';
body+='&SIGNATURE=AxWyhYIg8D5KIXCwlhj3d1yBOn5zA2AugWOKqAHk0m2a2LNdYhF9xUIi';
body+='&METHOD=DoReauthorization';
body+='&AUTHORIZATIONID=9CG092774F153364B';
body+='&AMT=20';
body+='&VERSION=115';
var Request=nlapiRequestURL(PaymentURl,body,null,'POST');
var requestBody=Request.getBody();
nlapiLogExecution('Debug','DoReauthorization',requestBody);

var PaymentURl='https://api-3t.sandbox.paypal.com/nvp';
var body='';
body+='&USER=vamsi-facilitator_api1.netscoretech.com';
body+='&PWD=BJR5MNVD3QRW65TU';
body+='&SIGNATURE=AxWyhYIg8D5KIXCwlhj3d1yBOn5zA2AugWOKqAHk0m2a2LNdYhF9xUIi';
body+='&METHOD=DoVoid';
body+='&AUTHORIZATIONID=64W85531CK482983S'//+TranId;
body+='&VERSION=115';
var Request=nlapiRequestURL(PaymentURl,body,null,'POST');
var requestBody=Request.getBody();
nlapiLogExecution('Debug','DoVoid',requestBody);

var PaymentURl='https://api-3t.sandbox.paypal.com/nvp';
var body='';
body+='&USER=vamsi-facilitator_api1.netscoretech.com';
body+='&PWD=BJR5MNVD3QRW65TU';
body+='&SIGNATURE=AxWyhYIg8D5KIXCwlhj3d1yBOn5zA2AugWOKqAHk0m2a2LNdYhF9xUIi';
body+='&METHOD=RefundTransaction';
body+='&TRANSACTIONID=7RA40945HS9597814'//+TranId;
body+='&REFUNDTYPE=Partial';
body+='&AMT=2'
body+='&VERSION=115';
var Request=nlapiRequestURL(PaymentURl,body,null,'POST');
var requestBody=Request.getBody();
nlapiLogExecution('Debug','RefundTransaction',requestBody);
var XXX=0;